using System.Reflection;
using System.Xml.Linq;

namespace XamlNexus.Common.Generators {
    public abstract class BaseGenerator : IGenerator {
        public abstract void Generate(ProjectConfig config);

        protected bool IsTextFile(string path) {
            string ext = Path.GetExtension(path).ToLower();
            string[] textExts = { ".cs", ".xaml", ".csproj", ".sln", ".slnx", ".json", ".xml", ".config", ".txt", ".md" };
            return textExts.Contains(ext);
        }

        protected void InjectProjectMetadata(string csprojPath, string templateType) {
            if (!File.Exists(csprojPath)) return;

            var doc = XDocument.Load(csprojPath);
            var project = doc.Root;
            if (project == null) return;

            // 找或创建带 Label 的 PropertyGroup
            var propertyGroup = project.Elements("PropertyGroup")
                .FirstOrDefault(x => x.Attribute("Label")?.Value == "XamlNexus");

            if (propertyGroup == null) {
                propertyGroup = new XElement("PropertyGroup",
                    new XAttribute("Label", "XamlNexus"));
                project.Add(propertyGroup);
            }

            // 获取版本号（x.x.x）
            string version = GetGeneratorVersion();

            SetOrUpdate(propertyGroup, "Description", "Generated by XamlNexus Generator");
            SetOrUpdate(propertyGroup, "XamlNexusVersion", version);
            SetOrUpdate(propertyGroup, "XamlNexusTemplate", templateType);

            doc.Save(csprojPath);
        }

        protected virtual string GetGeneratorVersion() {
            var assembly = Assembly.GetExecutingAssembly();

            // 优先取 InformationalVersion（支持语义化版本，比如 1.2.3+commit）
            var infoVersion = assembly
                .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                ?.InformationalVersion;

            string version = infoVersion
                ?? assembly.GetName().Version?.ToString()
                ?? "1.0.0";

            // 截取前三段 x.x.x
            var parts = version.Split('.', '-', '+'); // 兼容 1.2.3-beta
            return parts.Length >= 3
                ? $"{parts[0]}.{parts[1]}.{parts[2]}"
                : version;
        }

        private void SetOrUpdate(XElement parent, string name, string value) {
            var element = parent.Element(name);
            if (element == null) {
                parent.Add(new XElement(name, value));
            }
            else {
                element.Value = value;
            }
        }
    }
}
